import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";

const chillax = localFont({
  src: "../public/fonts/Chillax-Regular.otf",
  variable: "--font-chillax",
});

const clash = localFont({
  src: "../public/fonts/ClashDisplay-Regular.otf",
  variable: "--font-clash",
});

export const metadata: Metadata = {
  title: "Finalysis - Arijit De",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        chillax.variable,
        clash.variable,
        "font-clash"
      )}
    >
      <body className="min-h-full flex flex-col overflow-x-hidden">{children}</body>
    </html>
  );
}
