'use client';

import { useState, useEffect } from "react";
import SoftBoxBlurBg from "@/components/SoftBoxBlurBg";
import Lenis from "lenis";
import GradualBlur from "@/components/GradualBlur";
import { Scale, Info, CheckCircle2, ShieldAlert, Award, FileText } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsAndConditions() {
  const [isLoaded, setIsLoaded] = useState(false);
  const [mounted, setMounted] = useState(false);

  // Lenis smooth scrolling
  useEffect(() => {
    const lenis = new Lenis({
      duration: 1.2,
      easing: (t) => Math.min(1, 1.001 - Math.pow(2, -10 * t)),
      smoothWheel: true,
    });
    let rafId: number;
    function raf(time: number) {
      lenis.raf(time);
      rafId = requestAnimationFrame(raf);
    }
    rafId = requestAnimationFrame(raf);
    return () => {
      lenis.destroy();
      cancelAnimationFrame(rafId);
    };
  }, []);

  // Mount animation
  useEffect(() => {
    setMounted(true);
    document.title = "Terms & Conditions | FinAnalysis";
    const timer = setTimeout(() => {
      setIsLoaded(true);
    }, 100);
    return () => clearTimeout(timer);
  }, []);

  const sections = [
    {
      id: "acceptance-terms",
      icon: <CheckCircle2 className="w-5 h-5 text-primary" />,
      title: "Acceptance of Terms",
      content: (
        <p className="font-sans text-sm text-muted-foreground leading-relaxed">
          By accessing, browsing, or utilizing the FinAnalysis platform (including our calculators, onboarding portals, and automated advisory resources), you acknowledge that you have read, understood, and agreed to be legally bound by these Terms and Conditions. If you do not accept these terms in their entirety, you are requested to discontinue the use of our services immediately.
        </p>
      )
    },
    {
      id: "regulatory-disclosures",
      icon: <Award className="w-5 h-5 text-primary" />,
      title: "Regulatory & Distributor Disclosures",
      content: (
        <div className="space-y-3 font-sans text-sm text-muted-foreground leading-relaxed">
          <p>
            FinAnalysis operates as a regulated financial advisory and distribution platform. Please note the following status details:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li><strong>SEBI Registration:</strong> Mutual Fund Distribution services are offered under SEBI-registered ARN (AMFI Registration Number) <strong>ARN-273396</strong> issued to <strong>Arijit De</strong>.</li>
            <li><strong>Product Scope:</strong> We act as an intermediary distributor for Mutual Funds, Specialised Investment Funds (SIF), Fixed Deposits, Life/Health/General Insurance, and PNB Housing Finance products.</li>
            <li><strong>Commission Structure:</strong> In accordance with SEBI guidelines, we disclose that we receive commission fees directly from asset management companies (AMCs) and insurance providers for transactions routed through our ARN.</li>
          </ul>
        </div>
      )
    },
    {
      id: "market-risk-disclaimer",
      icon: <ShieldAlert className="w-5 h-5 text-primary" />,
      title: "Market Risk & Advisory Disclaimers",
      content: (
        <div className="space-y-3 font-sans text-sm text-muted-foreground leading-relaxed">
          <p className="font-semibold text-amber-700 bg-amber-500/10 border border-amber-500/20 p-3.5 rounded-2xl">
            ⚠️ Mutual Fund investments are subject to market risks. Please read all scheme-related documents carefully before investing. Past performance is not indicative of future yields.
          </p>
          <p>
            All evaluations, metrics, scores, and projections generated by our automated diagnostic tools (such as our calculator models or Your AI assistant) represent hypothetical simulations. They do not constitute formal binding guarantees or legal underwriting. Clients must evaluate their financial position and consult registered advisors before committing capital.
          </p>
        </div>
      )
    },
    {
      id: "user-accounts",
      icon: <Info className="w-5 h-5 text-primary" />,
      title: "User Responsibilities & Accounts",
      content: (
        <div className="space-y-3 font-sans text-sm text-muted-foreground leading-relaxed">
          <p>
            When utilizing our onboarding system or user dashboard, you agree to:
          </p>
          <ul className="list-disc pl-5 space-y-1">
            <li>Provide true, accurate, and current personal and financial credentials.</li>
            <li>Maintain absolute confidentiality of your login sessions and OTP verification prompts.</li>
            <li>Refrain from reverse-engineering the diagnostic algorithms, calculator logic, or scraping codebase assets.</li>
            <li>Acknowledge that unauthorized uploads of falsified PAN, Aadhaar, or AMC statements are strictly prohibited and may result in immediate profile termination.</li>
          </ul>
        </div>
      )
    },
    {
      id: "intellectual-property",
      icon: <FileText className="w-5 h-5 text-primary" />,
      title: "Intellectual Property Rights",
      content: (
        <p className="font-sans text-sm text-muted-foreground leading-relaxed">
          The code structure, bento designs, computational formulas, calculator algorithms, branding elements, and copy displayed on the FinAnalysis platform are the exclusive intellectual property of FinAnalysis (and its developers/licensors). No content may be replicated, distributed, or modified without explicit written authorization from us.
        </p>
      )
    },
    {
      id: "limitation-liability",
      icon: <Scale className="w-5 h-5 text-primary" />,
      title: "Limitation of Liability & Jurisdiction",
      content: (
        <p className="font-sans text-sm text-muted-foreground leading-relaxed">
          FinAnalysis, its founders, and employees will not be held liable for any direct, indirect, incidental, or consequential losses resulting from market declines, investment choices, technical platform downtime, or dependencies placed on automated diagnostic advice. These terms shall be governed by and construed in accordance with the laws of India. Any legal disputes arising under these conditions shall be subject to the exclusive jurisdiction of the competent courts in Kolkata, West Bengal.
        </p>
      )
    }
  ];

  return (
    <main className="relative min-h-screen w-full bg-transparent text-foreground flex flex-col font-clash">
      {/* Fixed Background container with User's Gradient Theme */}
      <div className="fixed inset-0 z-0 select-none pointer-events-none bg-[#F2F0EF] bg-[radial-gradient(circle_at_bottom,rgba(147,197,253,0.95)_0%,rgba(186,230,253,0.65)_45%,rgba(242,240,239,0)_85%)]">
        <SoftBoxBlurBg />
      </div>

      <Navbar isLoaded={isLoaded} />

      {/* Header Title Section */}
      <div className="relative z-10 flex flex-col justify-center items-center px-6 pt-44 pb-6 text-center max-w-5xl mx-auto">
        <h1
          className={`text-4xl md:text-7xl font-normal tracking-tight mt-12 mb-4 leading-none text-primary font-clash transition-all duration-[1200ms] ease-out ${isLoaded ? "opacity-100 blur-none scale-100" : "opacity-0 blur-lg scale-95"
            } delay-[200ms]`}
        >
          Terms & Conditions
        </h1>
        <p
          className={`text-sm md:text-base text-muted-foreground max-w-xl mx-auto mb-10 leading-relaxed font-sans transition-all duration-[1200ms] ease-out ${isLoaded ? "opacity-100 blur-none scale-100" : "opacity-0 blur-md scale-95"
            } delay-[400ms]`}
        >
          Last updated: June 6, 2026. Please read these terms carefully before accessing our advisory platform and calculators.
        </p>
      </div>

      {/* Main Content Layout */}
      <div
        className={`relative z-10 w-full max-w-5xl mx-auto px-6 pb-36 grid grid-cols-1 lg:grid-cols-12 gap-10 transition-all duration-[1200ms] ease-out ${isLoaded ? "opacity-100 translate-y-0" : "opacity-0 translate-y-12"
          } delay-[500ms]`}
      >
        {/* Left Column: Quick Navigation Menu (Hidden on mobile) */}
        <div className="hidden lg:block lg:col-span-4 self-start sticky top-32 bg-white/20 border border-border rounded-3xl p-6 shadow-sm backdrop-blur-2xl">
          <span className="text-[10px] font-mono text-muted-foreground uppercase tracking-widest block mb-4">Table of Contents</span>
          <nav className="flex flex-col gap-3 font-sans text-sm text-left">
            {sections.map((sec) => (
              <a
                key={sec.id}
                href={`#${sec.id}`}
                className="text-muted-foreground hover:text-primary transition-colors duration-200 py-1.5 border-b border-border/10 last:border-0 hover:pl-1 transition-all duration-200"
              >
                {sec.title}
              </a>
            ))}
          </nav>
        </div>

        {/* Right Column: Content */}
        <div className="lg:col-span-8 bg-white/35 border border-border rounded-3xl p-8 md:p-10 shadow-md backdrop-blur-2xl space-y-10 flex flex-col justify-center text-left">
          {sections.map((sec) => (
            <div key={sec.id} id={sec.id} className="space-y-4 scroll-mt-32">
              <div className="flex items-center gap-3 border-b border-border/40 pb-2">
                {sec.icon}
                <h2 className="text-lg md:text-xl font-bold text-primary font-clash tracking-wide">
                  {sec.title}
                </h2>
              </div>
              {sec.content}
            </div>
          ))}
        </div>
      </div>

      <Footer />

      {isLoaded && (
        <GradualBlur preset="page-footer" height="2rem" style={{ zIndex: 30 }} />
      )}
    </main>
  );
}
